import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "../components/Header";
import { UserProvider } from "../state";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className="p-4">
          <UserProvider>
            <Header />

            {children}
          </UserProvider>
        </div>
      </body>
    </html>
  );
}
